tasks:
  - init: pip install isort mypy pylint flake8 autopep8
    command: pip install --no-cache-dir -r requirements.txt

vscode:
  extensions:
    - ms-python.python
    - ms-pyright.pyright
    - matangover.mypy
    - magicstack.magicpython